image: node:16.14.0

# Instance is run in a single stage because the server doesn't allow artifacts
# to be stored when they are in this size

stages:
  - test

test:
  stage: test
  script:
    - npm install
    - npm run build
    - npm run lint
    - npm run test:coverage
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
#stages:
#  - install
#  - build
#  - quality
#
#install:
#  stage: install
#  script:
#    - npm install
#
#build:
#  stage: build
#  script:
#    - CI=false npm run build
#  artifacts:
#    paths:
#      - build
#    expire_in: 60 mins
#  dependencies:
#    - install
#
#linting:
#  stage: quality
#  script:
#    - npm run lint
#  dependencies:
#    - install
#
#test:unit:
#  stage: quality
#  script:
#    - npm run test:coverage
#  dependencies:
#    - install
#  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
